@startuml
|Аналітик\nобстановки|
start

:Класифікувати\nтрек цілі;
|Оперативний\nчерговий|
if (Ворожа?) then (так)
  :Підтвердити\nціль;
else (ні)
  :Залишити під\nспостереженням;
  stop
endif
|Офіцер бойового\nуправління|
:Перевірити\nдеконфлікцію;
if (Конфлікт?) then (так)
  :Запросити\nпогодження;
  stop
else (ні)
endif
repeat
  :Обрати\nрозрахунок;
  |Оперативний\nчерговий|
  :Розглянути\nпуск;
repeat while (Дозволено?) is (ні) not (так)
stop
@enduml
