@startuml
|Офіцер бойового\nуправління|
start
:Передати\nбойове завдання;
|Командир\nрозрахунку|
if (Завдання\nвиконуване?) then (так)
  :Підтвердити\nприйняття;
else (ні)
  :Надіслати\nвідмову;
  stop
endif
|Оператор\nперехоплювача|
fork
  :Підготувати\nмаршрут;
fork again
  :Передпольотний\nконтроль;
end fork
:Здійснити\nпуск;
if (Ціль\nвиявлено?) then (так)
  :Підтвердити ціль\nу фазі наведення;
else (ні)
endif
|Командир\nрозрахунку|
:Доповісти\nпро результат;
stop
@enduml
